### PR TITLE
Add rollable state to dims and use in control widget

### PR DESCRIPTION
**Pull request by andy-sweet**
This is a quick prototype to show an alternative approach for https://github.com/napari/napari/pull/5986

### CODE REVIEW

**Comment by Chris-N-K** [comment]
I think this solution looks promising.
It would probably be good if unchecked dimensions are no longer draggable.
I think we can add this as a event callback to the QtAxisList toggling the properties of the underlying items.
I have a working solution in plain qt will try to implement this.

**Comment by Chris-N-K** [comment]
I noticed that in the current implementation the rolling logic seems to be corrupted.

**Comment by andy-sweet** [comment]
> I noticed that in the current implementation the rolling logic seems to be corrupted.

There could definitely be bugs here! I did some very light testing and things worked as expected, but I almost certainly missed some things.

**Comment by Chris-N-K** [comment]
Seems to be the same issue I encountered from time to time. I can not really reproduce it. Sometimes the order list seems to get clipped for what ever reason. The rest looks like it all works out.

I tried to implement to make the items unselectable if the rollable value is false, but could not figure out to do it yet. Flags do not work as is seems.

In my reference implementation I connected the dataChanged event of the underlying model with a callback that toggles the item properties. Due to the structure of the QAbstractItemModel derived classes I can not really do that.

**Comment by Chris-N-K** [comment]
I figured out how to make the items nondragable :) and made a pull request.

**Comment by Chris-N-K** [comment]
And I found the scenario in which the error occurs, can reproduce it now. Would you test it yourself?
Just add an layer to the viewer (I used 4 dims) and directly open the QtDimsSorter pop-up and drag an item. Should cause an KeyError. Roll through the dims with the button before opening the pop-up everything works nicely. Guess something is not initialized correctly.

**Comment by andy-sweet** [comment]
@Chris-N-K : made some small changes. We still have some failing tests for the sorter because a parent (specifically a `QDialog`) is not specified there. I think we can fix that over on your PR, maybe with some other community feedback.

**Review by Chris-N-K — APPROVED** [review]
All good

**Comment by andy-sweet** [comment]
This was adopted in https://github.com/napari/napari/pull/5986

**Pull request closed without merging**
